version: "3.8"

x-environment-vars: &shared_environment
  - OMP_NUM_THREADS: ${OMP_NUM_THREADS:-8}
  - MKL_NUM_THREADS: ${MKL_NUM_THREADS:-8}
  - APPUSER: ${APPUSER:? username is not set}

services:
  app:
    image: ubuntu:latest
    container_name: app
    build:
      context: .
      args:
        APPUSER: ${APPUSER:?username is not set}
    shm_size: '8gb'
    volumes:
      - .:/home/${APPUSER}/app
    command: ["tail","-f","/dev/null"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    environment:
      <<: *shared_environment

  logs:
    image: ubuntu:latest
    container_name: logs
    build:
      context: .
      args:
        APPUSER: ${APPUSER:?username is not set}
    shm_size: '4gb'
    volumes:
      - ${LOG_DIR}:/home/${APPUSER}/logs
    ports:
      - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
    command: ["tensorboard","--logdir","/logs","--port",$TENSORBOARD_PORT, "--host","0.0.0.0"] 
    environment:
      <<: *shared_environment

  notebook:
    image: ubuntu:latest
    container_name: notebook
    build:
      context: .
      args:
        APPUSER: ${APPUSER:?username is not set}
    shm_size: '4gb'
    volumes:
      - .:/home/${APPUSER}/app
    ports:
      - ${NOTEBOOK_PORT}:${NOTEBOOK_PORT}
    command: ["jupyter","notebook","--ip","0.0.0.0","--port",$NOTEBOOK_PORT] 
    environment:
      <<: *shared_environment

